name: weeknd-pro
#why we rename: Without an explicit name, compose uses the directory name (infra) as the project prefix which describes the directory ,not the project.
#What happend before when name was not added: Containers got named as infra-auth-db-1 etc. Setting then name as weekend-pro makes them weekend-pro-auth-db-1 which is self documenting
services:
  auth-db:
    image: postgres:16
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  
  auth-db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80' # pgAdmin listens on 80 inside the container; reach it at http://localhost:5050
    depends_on:
      - auth-db
    restart: unless-stopped

  auth-service:
    build: ../services/auth
    env_file:
      - ../.env
    ports:
      - '3001:3001'
    depends_on:
      auth-db:
        condition: service_healthy
    restart: unless-stopped

  gateway-service:
    build: ../services/gateway
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
    restart: unless-stopped

volumes:
  auth-db-data:
